# Generated by Django 5.2.8 on 2025-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('STUDENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(default='Doctor', max_length=45)),
                ('COUNTRY_CODE', models.IntegerField()),
                ('MOBILE_NO', models.CharField(max_length=16)),
                ('EMAIL', models.CharField(max_length=63, unique=True)),
                ('EMAIL_VERIFIED', models.BooleanField()),
                ('EDUCATION', models.CharField(blank=True, max_length=30, null=True)),
                ('COLLEGE', models.CharField(blank=True, max_length=255, null=True)),
                ('ADDRESS_STATE', models.CharField(blank=True, max_length=150, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=512, null=True)),
                ('PROFILE_STATUS', models.CharField(max_length=20)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('DELETED', models.BooleanField()),
                ('UNIQUE_TOKEN', models.CharField(blank=True, max_length=255, null=True)),
                ('DEVICE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('OTP', models.CharField(blank=True, max_length=6, null=True)),
                ('OTP_SENT_AT', models.DateTimeField(blank=True, null=True)),
                ('FORGOT_PASSWORD_SENT_AT', models.DateTimeField(blank=True, null=True)),
                ('PASSWORD_UPDATED_AT', models.DateTimeField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'STUDENT',
                'managed': False,
            },
        ),
    ]
